### ISSUE TITLE
When VT100 color mode not selected, cls command does an incomplete sceen clear.

### ISSUE THREAD

**Issue by grymoire** [DangerousPrototypes/BusPirate5-firmware#117]
I (1) connected to the BP, (2) enabled VT100 display., (3) reconnected to the BP, (4) did NOT select the vt100 display.

As this point the VT100 display was still shown (reported  in issue #102 )
I typed "cls"
and the color bars disappeared, but the screen still showed on the bottom
```
HiZ> cls

HiZ> 

1.Vout  2.IO0   3.IO1   4.IO2   5.IO3   6.IO4   7.IO5   8.IO6   9.IO7   10.GND
OFF     -       -       -       -       -       -       -       -       GND
0.0V    0.0V    0.0V    0.0V    0.0V    0.0V    0.0V    0.0V    0.0V    GND
```

I would expect the entire screen to be cleared.

**Comment by DangerousPrototypes** [comment]
Improved switching between VT100 and ASCII. cls is no longer supported in ASCII because it uses VT100 code and so... is not supported.
