### ISSUE TITLE
Missing NACK when reading in I2C mode

### ISSUE THREAD

**Issue by myinternetofthings** [DangerousPrototypes/BusPirate5-firmware#12]
Reading I2C eeprom (24C64) content last byte before stop is ACKed instead of NACKed.

Steps to reproduce:
1. Switch to I2C mode
2. Connect eeprom
3. Enable power, and pullups
4. Execute command: `[0xa0 0x0 0x0 [0xa1 r:10]`

Actual behavior:
Last read byte is ACK instead of NACK
```
I2C START
TX: 0xA0 ACK 0x00 ACK 0x00 ACK
I2C START
TX: 0xA1 ACK
RX: 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK
    0x00 ACK 0x00 ACK
I2C STOP
```

Expected behavior:
Last read byte is NACKed
```
I2C START
TX: 0xA0 ACK 0x00 ACK 0x00 ACK
I2C START
TX: 0xA1 ACK
RX: 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK 0x00 ACK
    0x00 ACK 0x00 NACK
I2C STOP
```

I suspect that hardcoded bytecode is a problem in line:
https://github.com/DangerousPrototypes/BusPirate5-firmware/blob/0a5dc67957bcef892ce7499f6efc10939f3f00cd/mode/hwi2c.c#L137
Use constants from bytecode.h instead.
Both 
https://github.com/DangerousPrototypes/BusPirate5-firmware/blob/main/bytecode.h#L50 
and 
https://github.com/DangerousPrototypes/BusPirate5-firmware/blob/main/bytecode.h#L52 
should be accepted

Workaround:
Use START_ALT syntax `{` just before stop to trigger NACK on read:
`[0xa0 0x0 0x0 [0xa1 r:10{]`

**Comment by DangerousPrototypes** [comment]
Thank you so much for this bug report. The enum of the bytecode changed recently when I tweaked something in SPI mode and it introduced this bug with the hard coded number instead of a define.

>RX: 0xFF ACK 0xFF ACK 0xFF ACK 0xFF NACK

A fix is tested and pushed. I also included stop, start_alt and stop_alt so repeated starts should hopefully be NAKed correctly as well.
