### ISSUE TITLE
SPI CLK polarity issues in fala mode

### ISSUE THREAD

**Issue by ilw** [DangerousPrototypes/BusPirate5-firmware#124]
SPI clock polarity setting seems to be ignored (at least in follow along analyzer mode). (Idle high mode doesn't work)

Also seems to cause an error when aksed if you want to reuse the previous settings (the line for clock polarity says "1 to 62500khz)

Use previous settings?
 SPI speed: 100 kHz
 Data bits: 8
 Clock polarity: 1 to 62500kHz
 Clock phase: LEADING edge
 Chip select: Active LOW (/CS)

**Comment by DangerousPrototypes** [comment]
I fixed this one.
