### ISSUE TITLE
BusPirate5 Rev 8 does not mount /media/$USER/BUS_PIRATE5

### ISSUE THREAD

**Issue by grymoire** [DangerousPrototypes/BusPirate5-firmware#131]
Minor issue with BP5 Beta rev 8: 
Using version 
```
Bus Pirate 5 REV8
Firmware main branch @ unknown (2024-10-12T17:20:50Z)
RP2040 with 264KB RAM, 128Mbit FLASH
S/N: 251821CB83B062E4
https://BusPirate.com/
Storage:   2.75GB (FAT32 File System)
```
When I plug it in, it mounts /media/$USER/5021-0000
instead of /media/$USER/BUS_PIRATE5

**Comment by mbrugman67** [comment]
Out of curiosity, if you unplug the BP, do a `systemctl restart udev` (or init.d script, or whatever based on your distro), and plug it back in again, does it mount as `BUS_PIRATE`?  

During all of the storage corruption testing, I found that my REV10 BP would start doing that (and other issues) until I restarted udev.  Rebooting Linux would do the same, but restarting udev is much less disruptive :)
