### ISSUE TITLE
A space character causes a syntax error

### ISSUE THREAD

**Issue by grymoire** [DangerousPrototypes/BusPirate5-firmware#152]
The command "[]" works, yet if I put a space before it, it causes a syntax error
```
I2C> []

I2C START
I2C STOP

I2C>  []
Invalid command: []. Type ? for help.

```
This can be a problem when a beginner copies and pastes sample scripts. They paste the "exact same thing" (with an extra space from the copy process), and then they get a syntax error.

**Comment by DangerousPrototypes** [comment]
Fixed, thank you for the bug report.
