### ISSUE TITLE
Help does not fit on screen

### ISSUE THREAD

**Issue by ralphrmartin** [DangerousPrototypes/BusPirate5-firmware#35]
Typing h to get a list of commands scrolls of the top, so the full list of commands cannot be seen - even whgen using a very large window:
![Screenshot 2024-04-24 at 21 25 12](https://github.com/DangerousPrototypes/BusPirate5-firmware/assets/5293194/8b9b8315-644a-4a74-af2d-94467852508e)

**Comment by lersi** [comment]
I have this issue too, possible solution can be adding a pause in the firmware.

In screen, you have a work around, use screen's escape sequence, and then press the actual escape key,
it will give you the option to "go around" in the terminal, including previous lines
