### ISSUE TITLE
Internal file system kept getting corrupted

### ISSUE THREAD

**Issue by TwistedSim** [DangerousPrototypes/BusPirate5-firmware#60]
Everytime I try to use the internal file system, it seems to get corrupted. It briefly work after using the "format" command, but then, it stopped working properly. Here what the ls command output when the FS is corrupted:

![image](https://github.com/DangerousPrototypes/BusPirate5-firmware/assets/12924452/6c8dfc58-3343-4af2-87dc-c26910cb37ed)

**Comment by wyattearp** [comment]
@TwistedSim - could you provide some of the following information to help triage?
* Hardware Version (8 / 10) ?
* Software Version or git tag?
* Host operating system and version?
* Steps to reproduce?

Thanks!

**Comment by TwistedSim** [comment]
Hello! 

- Bus Pirate 5 REV10
- Firmware main branch (2024-06-09T09:54:04Z) [929d4c5…967019d]
- Ubuntu 20.04 LTS
- It keeps happening randomly, so it's hard to pin point precise steps. I was mostly using the SPI module (flash init, read, write) and sending manual command (e.g. `[0x03 ... ]`).

**Comment by TwistedSim** [comment]
might be related:
![image](https://github.com/DangerousPrototypes/BusPirate5-firmware/assets/12924452/f04bcb36-6eb3-4765-a52b-bf4dd9b43821)
