### ISSUE TITLE
No devices found in 1-Wire mode

### ISSUE THREAD

**Issue by jonaskohlbrenner** [DangerousPrototypes/BusPirate5-firmware#88]
Hi all,

I just updated the firmware of my BP5 rev10 to [@bbcff78](https://github.com/DangerousPrototypes/BusPirate5-firmware/commit/bbcff785664f5c72bcdb38905f650eb1c30c1619) from [@82d86ab](https://github.com/DangerousPrototypes/BusPirate5-firmware/commit/82d86aba4746b3e52328d2e7f14485032bce6db2).
Afterwards, BP doesn't find devices when in 1-Wire mode:
<img width="450" alt="grafik" src="https://github.com/user-attachments/assets/c2f865cc-c2a5-48ff-a809-3725db24ec24">

I have attached a ds18b20 (1-Wire) which works fine with the @82d86ab firmware:
<img width="450" alt="grafik" src="https://github.com/user-attachments/assets/d6b23a04-6424-4b10-bc63-38c1652aa74c">

1-Wire already stops working with the [@ab07ef0](https://github.com/DangerousPrototypes/BusPirate5-firmware/commit/ab07ef0fa380999f9050b7a69554e23039f89b2c) commit (various bug fixes, new bugs introduced probably 😁) so I guess something was broken there.

Would be great if someone could have a look.
Thanks!

**Comment by DangerousPrototypes** [comment]
I believe this was due to issues in PICO SDK2.0. I reverted to manually assigning the PIO resources and 1-wire has been tested to work on all hardware.
